[sc-311] fix ref to ref removal pass
HigherOrderCO/hvm-lang pull request #100
Opened 2024-01-10 14:57 UTC by LunaAmora

This pr implements the first option described in the task:

1. One would be to have main be a duplicate of the function it's referencing. This is the simplest option.
2. Another option would be to have the other function be merged with main, replacing all call to it with calls to main.

2024-01-10 17:39 UTC, developedby requested changes

2024-01-10 17:39 UTC, developedby commented on src/term/transform/simplify_ref_to_ref.rs
> +    if let Term::Ref { def_id } = &self.defs.get(&main).unwrap().rules[0].body {
Can you just add a comment explaining why we do this `if`?

2024-01-15 13:48 UTC, developedby commented
I think we can do without this pass at all. With compile-time reduction and later inlining, we will achieve the same results.

But this is not super high priority, so I'll come back later to decide what to do with this PR.

2024-01-16 13:09 UTC, LunaAmora commented
> I think we can do without this pass at all. With compile-time reduction and later inlining, we will achieve the same results.
> 
> But this is not super high priority, so I'll come back later to decide what to do with this PR.

As can be observed on this [str task](https://app.shortcut.com/hocomp/story/338/function-pattern-matching-fails-on-num-and-var), i don't think the other passes are achieving the desired results, as a main that is only a ref to another function causes hvm-core to have non-deterministic results. 

Or did you mean we could have this fixed when we improve the other passes and remove this one?

2024-01-16 13:27 UTC, imaqtkatt approved these changes

2024-01-16 15:03 UTC, developedby approved these changes

2024-01-16 16:10 UTC, merged