[sc-402] Refactor var-use counting when linearizing
HigherOrderCO/hvm-lang pull request #195
Opened 2024-02-16 18:32 UTC by LunaAmora

2024-02-16 18:54 UTC, imaqtkatt approved these changes

2024-02-19 10:55 UTC, developedby requested changes

2024-02-19 10:55 UTC, developedby commented on src/term/transform/linearize.rs
> +#[allow(dead_code)]
Why not remove this?

2024-02-19 10:55 UTC, developedby commented on src/term/transform/linearize.rs
> +#[allow(dead_code)]
also this

2024-02-19 11:21 UTC, developedby approved these changes

2024-02-19 11:38 UTC, merged