configure ci
HigherOrderCO/hvm-lang pull request #204
Opened 2024-02-23 18:14 UTC by tjjfvi

I was setting up CI for hvm-core; figured it might be useful here too.

Configures GitHub Actions to automatically check/test/lint/fmt/spellcheck PRs.

Looks like a test is currently failing (`tests/snapshots/compile_file_o_all__black_box.hvm.snap`); cc @FranchuFranchu

2024-02-23 20:23 UTC, developedby requested changes
I've never configured a github CI myself, so I'll trust you that the details are correct.

2024-02-23 20:23 UTC, developedby commented on cspell.json
> +    "appllication's",
This is wrong appllication -> application.

2024-02-23 20:23 UTC, developedby commented on cspell.json
> +    "maximium",
maximium -> maximum

2024-02-23 20:23 UTC, developedby commented
What is the spell-checking tool you're using here?

2024-02-23 20:39 UTC, tjjfvi commented
Sorry, I reviewed the list of words for errors, but I guess I missed those two.

[cSpell](https://cspell.org/). I've used it a bit in the past, and have found it very helpful.

2024-02-26 11:51 UTC, developedby approved these changes

2024-02-26 14:32 UTC, merged