[sc 455] improve match linearization pass
HigherOrderCO/hvm-lang pull request #209
Opened 2024-02-26 16:42 UTC by LunaAmora

2024-02-26 16:57 UTC, imaqtkatt commented on src/lib.rs
> +    ctx.book.lift_combinators(matches!(opts.linearize_matches, OptLevel::Extra));
I think that it's better to change this `matches!` to an OptLevel method
`ctx.book.lift_combinators(opts.linearize_matches.is_extra())`

2024-02-26 19:28 UTC, imaqtkatt approved these changes

2024-02-27 11:52 UTC, developedby requested changes

2024-02-27 11:52 UTC, developedby commented on src/lib.rs
> +        "Warning: Running in strict mode without enabling the lift_combinators pass can lead to some functions expanding infinitely."
Add a similar comment for match linearization

2024-02-27 11:52 UTC, developedby commented on docs/compiler-options.md
> +| `-Olift_combinators` `-Ono-lift_combinators` | Enabled  | [lift-combinators](#lift-combinators) |
Can you add documentation on linearize-matches?

2024-02-27 11:52 UTC, developedby commented on src/term/transform/linearize_matches.rs
> +  pub fn linearize_matches(&mut self, linearize_extra: bool) -> Result<(), Info> {
linearize_extra is not very descriptive

2024-02-27 14:10 UTC, developedby requested changes

2024-02-27 14:10 UTC, developedby commented on docs/compiler-options.md
> +When `linearize-matches` linearizes only vars that are used in more than one arm.
When the `linearize-matches` option is used, ...

2024-02-27 14:10 UTC, developedby commented on docs/compiler-options.md
> +When `linearize-matches-extra`, linearizes all vars used in the arms.
Same here

2024-02-27 17:14 UTC, developedby approved these changes

2024-02-27 17:14 UTC, merged