[sc-460] Update tests to show HVM.log output
HigherOrderCO/hvm-lang pull request #228
Opened 2024-03-07 20:51 UTC by imaqtkatt

2024-03-08 13:54 UTC, developedby requested changes
Looks like one of the tests has changed

2024-03-08 13:54 UTC, developedby commented on tests/golden_tests.rs
> +        .args(["run", path.to_str().unwrap(), "-Dall", "-Oall", "-L"])
i think we have to add -Dall to the dictionary here

2024-03-08 14:28 UTC, LunaAmora commented
> Looks like one of the tests has changed

This is the same issue as we discoursed on discord [here](https://discord.com/channels/912426566838013994/1006963940649087018/1212760931231072306).

We need a different task implementing this [solution](https://discord.com/channels/912426566838013994/1006963940649087018/1212763229516726292) you suggested to fix it.

2024-03-08 14:36 UTC, LunaAmora approved these changes

2024-03-08 15:10 UTC, developedby commented
> > Looks like one of the tests has changed
> 
> This is the same issue as we talked about on discord [here](https://discord.com/channels/912426566838013994/1006963940649087018/1212760931231072306).
> 
> We need a different task implementing this [solution](https://discord.com/channels/912426566838013994/1006963940649087018/1212763229516726292) you suggested to fix it.

I thought we solved that already, but I guess not. @imaqtkatt can you open a new task for that?

2024-03-11 11:45 UTC, developedby approved these changes

2024-03-11 12:00 UTC, LunaAmora approved these changes

2024-03-11 12:05 UTC, merged