Fix linearization bug with unused duplicated vars
HigherOrderCO/hvm-lang pull request #51
Opened 2023-11-24 15:01 UTC by LunaAmora

this code was compiling wrong:

```
main = @x @y let b = (+ y y); x
```

resulting in `(a ({2 b c} a))` instead of `(a (* a))`

2023-11-24 16:30 UTC, developedby requested changes

2023-11-24 16:30 UTC, developedby commented on src/term/transform/linearize.rs
> +          if uses != 0 {
Can you add a comment explaining why this is necessary?

2023-11-24 16:30 UTC, developedby commented on src/term/transform/linearize.rs
> +            let name = Name(format!("{nam_some}$used"));
Can you refactor this into a function or a lambda so that there's only one place deciding what the name of this generated variable is?

2023-11-24 16:30 UTC, developedby commented on src/term/transform/linearize.rs
> +        let used_counter = format!("{nam}$used");
here as well

2023-11-24 16:30 UTC, developedby commented on src/term/transform/linearize.rs
> +                let name = Name(format!("{nam_some}$used"));
also here

2023-11-24 19:05 UTC, imaqtkatt approved these changes

2023-11-27 15:09 UTC, developedby approved these changes

2023-11-27 15:09 UTC, merged