[sc-305] Simplify the generated encoding for pattern matching
HigherOrderCO/hvm-lang pull request #95
Opened 2024-01-09 14:57 UTC by LunaAmora

This pr deals with the this part of the task:

- [x] If we know an argument will not be used, we can not pass it forward, which reduces the number of generated nodes.

Making the current program and compilation of:
```rs
data MyType = (A a) | (B b) | (C c) | (D d1 d2) | (E e1 e2)

Foo (A a) = R0
Foo * = R1
```
```rs
Foo = @x (x Foo$A Foo$B Foo$C Foo$D Foo$E)
Foo$R0 = @a R0
Foo$R1 = @* R1
Foo$A = @a (Foo$R0 a)
Foo$B = @b (Foo$R1 (B b))
Foo$C = @c (Foo$R1 (C c))
Foo$D = @d1 @d2 (Foo$R1 (D d1 d2))
Foo$E = @e1 @e2 (Foo$R1 (E e1 e2))
```

into this:
```rs
Foo = @x (x Foo$A Foo$B Foo$C Foo$D Foo$E)
Foo$R0 = @a R0
Foo$R1 = @* R1
Foo$A = @a (Foo$R0 *)
Foo$B = @b (Foo$R1 *)
Foo$C = @c (Foo$R1 *)
Foo$D = @d1 @d2 (Foo$R1 *)
Foo$E = @e1 @e2 (Foo$R1 *)
```

Instead of merging the now identical definitions of `Foo$B & Foo$C` and `Foo$D & Foo$E`, this can be done in a later pass to merge all identical definitions without further complicating the pattern matching encoding pass.

2024-01-09 15:39 UTC, developedby requested changes

2024-01-09 15:39 UTC, developedby commented on src/term/transform/encode_pattern_matching.rs
> +  fn lambdas_usage(&self) -> Vec<Option<()>> {
Can't this just be a bool?

2024-01-09 15:39 UTC, developedby commented on src/term/transform/encode_pattern_matching.rs
> +  fn lambdas_usage(&self) -> Vec<Option<()>> {
This function name is a bit hard to understand. Something like `arg_vars_are_used` maybe? Not sure, this one is a bit hard.

2024-01-09 15:39 UTC, developedby commented on src/term/transform/encode_pattern_matching.rs
> +  // Returns a sequence representing whether the lambda arg is binded or ignored
Can you add an example? Like `@a @* (a @x x) -> vec![true, false]`.

2024-01-09 15:41 UTC, developedby requested changes

2024-01-09 15:41 UTC, developedby commented on src/term/transform/encode_pattern_matching.rs
> +  // The lambdas  of the rule we're calling
This comment is not very descriptive.
I think "Whether the args of the rule we're calling are used" is a bit better.

2024-01-09 18:22 UTC, imaqtkatt approved these changes

2024-01-10 12:13 UTC, developedby approved these changes

2024-01-10 14:48 UTC, merged